"""add work status skill_tags updated_at

Revision ID: 1391ae1b978d
Revises: d64710a5542f
Create Date: 2026-07-31 18:26:14.840223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1391ae1b978d'
down_revision = 'd64710a5542f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_tags', sa.Text(), nullable=True, comment='技能标签ID数组，用于后续推流'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, comment='状态：draft/published/deleted'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('channel',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='渠道：writing/visual/video/voice',
               existing_nullable=True)
        batch_op.alter_column('files',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='文件URL数组',
               existing_nullable=True)
        batch_op.alter_column('cover_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='封面URL',
               existing_nullable=True)
        batch_op.alter_column('is_collaborative',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否协作作品',
               existing_nullable=True)
        batch_op.alter_column('collaborators',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='协作者用户ID数组',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('collaborators',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='协作者用户ID数组',
               existing_nullable=True)
        batch_op.alter_column('is_collaborative',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否协作作品',
               existing_nullable=True)
        batch_op.alter_column('cover_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='封面URL',
               existing_nullable=True)
        batch_op.alter_column('files',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='文件URL数组',
               existing_nullable=True)
        batch_op.alter_column('channel',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='渠道：writing/visual/video/voice',
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('skill_tags')

    # ### end Alembic commands ###
