"""add processed_at to project_applications

Revision ID: 3aeb772d0893
Revises: 9de4bb700c38
Create Date: 2026-07-31 20:10:21.553590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeb772d0893'
down_revision = '9de4bb700c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True, comment='审批时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_applications', schema=None) as batch_op:
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
