"""add password_hash to users

Revision ID: 60523706c09c
Revises: 7fb4b6a2aa10
Create Date: 2026-08-19 19:19:00.796407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60523706c09c'
down_revision = '7fb4b6a2aa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希（werkzeug）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
