"""profile v2: style_tags + experiences + ability_proofs + skills creator_id

Revision ID: 7467b5d1d7c1
Revises: 3aeb772d0893
Create Date: 2026-08-19 16:55:23.775465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7467b5d1d7c1'
down_revision = '3aeb772d0893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='风格词汇名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='词汇描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，越小越前'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ability_proofs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细介绍'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('school_level', sa.String(length=20), nullable=False, comment='学段：小学 / 中学 / 大学'),
    sa.Column('school_name', sa.String(length=100), nullable=False, comment='学校名称'),
    sa.Column('start_year', sa.Integer(), nullable=False, comment='入学年份，如2020'),
    sa.Column('end_year', sa.Integer(), nullable=True, comment='毕业年份，空=在读'),
    sa.Column('degree', sa.String(length=20), nullable=True, comment='学历层级：本科/硕士/博士（仅大学）'),
    sa.Column('major', sa.String(length=80), nullable=True, comment='专业名称（仅大学）'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_style_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('style_tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['style_tag_id'], ['style_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'style_tag_id', name='uq_profile_style_tag')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False, comment='公司名称'),
    sa.Column('position', sa.String(length=80), nullable=False, comment='职位名称'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='入职时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='离职时间，空=至今'),
    sa.Column('is_current', sa.Boolean(), nullable=True, comment='是否当前在职'),
    sa.Column('description', sa.Text(), nullable=True, comment='工作描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability_proof_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ability_proof_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='文件地址'),
    sa.Column('file_name', sa.String(length=200), nullable=True, comment='文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='image/pdf/doc/video等'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ability_proof_id'], ['ability_proofs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_experience_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False, comment='图片地址'),
    sa.Column('caption', sa.String(length=200), nullable=True, comment='图片说明'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', sa.String(length=30), nullable=False, comment='身份：学生 / 艺术爱好者 / 艺术相关工作者'))
        batch_op.drop_column('style_tags')
        batch_op.drop_column('identity_type')
        batch_op.drop_column('education')
        batch_op.drop_column('work_history')

    with op.batch_alter_table('skill_categories', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=mysql.INTEGER(),
               comment='排序',
               existing_comment='排序，越小越靠前',
               existing_nullable=True)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建者：0=平台预置，非0=用户自定义'))
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('skill_categories', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=mysql.INTEGER(),
               comment='排序，越小越靠前',
               existing_comment='排序',
               existing_nullable=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_history', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True, comment='工作经历'))
        batch_op.add_column(sa.Column('education', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True, comment='教育背景'))
        batch_op.add_column(sa.Column('identity_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='身份类型：amateur业余 / professional专业'))
        batch_op.add_column(sa.Column('style_tags', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True, comment='风格标签，JSON数组'))
        batch_op.drop_column('identity')

    op.drop_table('work_experience_images')
    op.drop_table('ability_proof_files')
    op.drop_table('work_experiences')
    op.drop_table('profile_style_tags')
    op.drop_table('education_experiences')
    op.drop_table('ability_proofs')
    op.drop_table('style_tags')
    # ### end Alembic commands ###
