"""batch2: project module fields + rating enhancement

Revision ID: 7fb4b6a2aa10
Revises: 7467b5d1d7c1
Create Date: 2026-08-19 17:03:17.086685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb4b6a2aa10'
down_revision = '7467b5d1d7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='标签名'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='positive 正向 / negative 负向 / neutral 中性'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_required_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False, comment='所需人数'),
    sa.Column('filled_count', sa.Integer(), nullable=True, comment='已招到人数（冗余）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_project_skill')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_user_id', sa.Integer(), nullable=True, comment='回复@的目标用户ID'))
        batch_op.create_foreign_key(None, 'users', ['reply_to_user_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True, comment='招募总人数上限'))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True, comment='项目封面'))
        batch_op.drop_column('required_skills')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True, comment='评价标签ID数组（JSON，见 rating_tags 字典）'))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True, comment='是否匿名评价'))
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               comment='分数 1-5',
               existing_nullable=False)
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='文字评价',
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_project_from_to', ['project_id', 'from_user_id', 'to_user_id'])

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True, comment='关联的协作项目ID'))
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论数（冗余）'))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_count')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_from_to', type_='unique')
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='文字评价',
               existing_nullable=True)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分数 1-5',
               existing_nullable=False)
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('tags')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_column('cover_url')
        batch_op.drop_column('max_members')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_to_user_id')

    op.drop_table('project_required_skills')
    op.drop_table('rating_tags')
    # ### end Alembic commands ###
