"""add follows table

Revision ID: d561fceb841e
Revises: 60523706c09c
Create Date: 2026-08-19 22:40:56.802696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd561fceb841e'
down_revision = '60523706c09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False, comment='关注者'),
    sa.Column('followed_id', sa.Integer(), nullable=False, comment='被关注者'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follower_followed')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_followed_id', ['followed_id'], unique=False)
        batch_op.create_index('ix_follower_id', ['follower_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('ix_follower_id')
        batch_op.drop_index('ix_followed_id')

    op.drop_table('follows')
    # ### end Alembic commands ###
