"""add skill tables and remove profile.skills json field

Revision ID: d64710a5542f
Revises: ed94894c6747
Create Date: 2026-07-31 18:16:12.594395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd64710a5542f'
down_revision = 'ed94894c6747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='分类编码'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，越小越靠前'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='技能名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_profile_skill')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('identity_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='身份类型：amateur业余 / professional专业',
               existing_nullable=True)
        batch_op.alter_column('style_tags',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='风格标签，JSON数组',
               existing_nullable=True)
        batch_op.alter_column('work_history',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='工作经历',
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='教育背景',
               existing_nullable=True)
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.alter_column('education',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='教育背景',
               existing_nullable=True)
        batch_op.alter_column('work_history',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='工作经历',
               existing_nullable=True)
        batch_op.alter_column('style_tags',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='风格标签，JSON数组',
               existing_nullable=True)
        batch_op.alter_column('identity_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='身份类型：amateur业余 / professional专业',
               existing_nullable=True)

    op.drop_table('profile_skills')
    op.drop_table('skills')
    op.drop_table('skill_categories')
    # ### end Alembic commands ###
