"""message module: notifications/conversations/groups/messages refactor

Revision ID: f5e51486cc72
Revises: d561fceb841e
Create Date: 2026-09-04 14:21:22.585149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5e51486cc72'
down_revision = 'd561fceb841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False, comment='用户1（约束 user1_id < user2_id）'),
    sa.Column('user2_id', sa.Integer(), nullable=False, comment='用户2'),
    sa.Column('last_message_content', sa.String(length=500), nullable=True, comment='冗余：最后一条消息预览'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='冗余：最后消息时间（排序用）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_conversation_users')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conv_user1_last', ['user1_id', 'last_message_at'], unique=False)
        batch_op.create_index('ix_conv_user2_last', ['user2_id', 'last_message_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收者'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='interaction 互动 / todo 待办'),
    sa.Column('subtype', sa.String(length=30), nullable=False, comment='interaction->like/comment/follow; todo->apply/pending_review/pending_invite'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='通知标题'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='通知内容'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='操作账号，系统待办=NULL'),
    sa.Column('related_type', sa.String(length=20), nullable=True, comment='被操作对象类型：work/project/user'),
    sa.Column('related_id', sa.Integer(), nullable=False, comment='被操作对象ID'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_noti_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_noti_user_type_read', ['user_id', 'type', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('conversation_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=True, comment='未读条数'),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True, comment='最后读到的消息ID'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conv_read_user')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='群名称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='群头像'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='群主'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目（协作群自动创建），自由群=NULL'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='冗余：成员数'),
    sa.Column('last_message_content', sa.String(length=500), nullable=True, comment='冗余：最后消息预览'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='冗余：最后消息时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True, comment='owner/admin/member'),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='群内昵称（可选）'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_table('group_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=True, comment='未读条数'),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True, comment='最后读到的消息ID'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_read_user')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_type', sa.String(length=10), nullable=False, comment='private=私聊 / group=群聊'))
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=True, comment='私聊会话ID，群聊为NULL'))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True, comment='群聊ID，私聊为NULL'))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送者'))
        batch_op.add_column(sa.Column('msg_type', sa.String(length=20), nullable=False, comment='text/image/voice/file/invite_project/invite_review/call'))
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True, comment='文件名（file 类型）'))
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小字节'))
        batch_op.add_column(sa.Column('voice_duration', sa.Integer(), nullable=True, comment='语音时长秒'))
        batch_op.add_column(sa.Column('related_type', sa.String(length=20), nullable=True, comment='关联类型：project 等'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='消息内容（文字/URL/JSON）',
               existing_nullable=False)
        batch_op.alter_column('related_id',
               existing_type=mysql.INTEGER(),
               comment='关联ID（项目邀请用 project_id）',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_msg_conv_time', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('ix_msg_group_time', ['group_id', 'created_at'], unique=False)
        batch_op.create_index('ix_msg_sender_time', ['sender_id', 'created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('from_user_id')
        batch_op.drop_column('is_read')
        batch_op.drop_column('to_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_official', sa.Boolean(), nullable=True, comment='0=普通用户，1=官方账号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_official')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('from_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_2'), 'users', ['to_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_1'), 'users', ['from_user_id'], ['id'])
        batch_op.drop_index('ix_msg_sender_time')
        batch_op.drop_index('ix_msg_group_time')
        batch_op.drop_index('ix_msg_conv_time')
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.alter_column('related_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联ID（项目邀请用 project_id）',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='消息内容（文字/URL/JSON）',
               existing_nullable=False)
        batch_op.drop_column('related_type')
        batch_op.drop_column('voice_duration')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('msg_type')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('group_id')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('conversation_type')

    op.drop_table('group_reads')
    op.drop_table('group_members')
    op.drop_table('groups')
    op.drop_table('conversation_reads')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_noti_user_type_read')
        batch_op.drop_index('ix_noti_user_created')

    op.drop_table('notifications')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conv_user2_last')
        batch_op.drop_index('ix_conv_user1_last')

    op.drop_table('conversations')
    # ### end Alembic commands ###
